name: Semantic Release

on:
  push:
    branches:
      - main

jobs:
  quality:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        os: [ubuntu-latest, macOS-latest, windows-latest]

    name: Run tests
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: Gr1N/setup-poetry@v8
      - name: Install dependencies
        run: poetry install
      - name: Run tests
        run: poetry run pytest

  release:
    needs: quality
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, 'chore(release):')
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

       - uses: Gr1N/setup-poetry@v8
      - name: Install dependencies
        run: poetry install

      - name: Python Semantic Release
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'action@github.com'
          poetry run semantic-release publish
        env:
          GH_TOKEN: ${{secrets.GH_TOKEN}}
          PyPI_TOKEN: ${{secrets.PyPI_TOKEN}}
